#!/usr/bin/env bash
# Displays numbers from 1 to 20 and the following
# the string "bad luck from China" in the 4th loop
# the string "bad luck from Japan" in the 9th loop
# the string "bad luck from Italy" in the 17th loop

i=1;

while [ $i -le 20 ]; do	
	if [ $i -eq 4 ]; then
		echo "$i"
		echo "bad luck from China"
	elif [ $i -eq 9 ]; then
		echo "$i"
		echo "good luck from Japan"
	elif [ $i -eq 17 ]; then
		echo "$i"
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	i=$((i+1)); 
done
