#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hour=1;

while [ $hour -le 12 ]; do
	min=1;
	while [ $min -le 59 ]; do
		echo "$min";
		min=$((min+1));
	done
	echo "Hour: $hour";
	hour=$((hour+1));
done
